# Git and Github

## Git setup

Set up your commit signature globally (for all repositories):

```sh
 
# Customize your git signature,
# the copy, paste and execute on Terminal

git config --global user.name "Andrea Melloncelli"
git config --global user.email andrea@vanlog.it
```

See also: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

## Add a remote to your locally created repository

Prerequisite: create a new RStudio project with git, with at least one commit.

In any empty github repository web page you can find these instructions.

Advice: select HTTPS protocol.

```sh
# or push an existing repository from the command line

# just in case, remove 'origin' if it already exists
git remote rm origin

git remote add origin https://github.com/andreamelloncelli/R-for-data-science-2022-collaboration.git
git branch -M main
git push -u origin main
```

You can verify the correct remote's configuration:

```sh
git remote -v
#> origin  https://github.com/andreamelloncelli/R-for-data-science-2022-collaboration.git (fetch)
#> origin  https://github.com/andreamelloncelli/R-for-data-science-2022-collaboration.git (push)
```

## Other CLI Git Operations

CLI means Command Line Interface, which is the "Command Prompt" on Windows, the Bash on Linux and MacOS.

```sh
# get the status
git status
# upload the latest modifications
git push
# download the latest modifications
git pull
# history
git log
# go to the branch main
git checkout main
# create a new branch
git branch work-in-progress
# move on that branch
git checkout work-in-progress
```



## Troubleshooting via CLI


### Pull

Remark: `pull` is the equivalent of the sequence of fetch and merge operations:

```sh
# download the latest modifications, without using them
git fetch
# merge you "main" branch with the remote version ("origin/main")
git merge origin/main
```

Therefore if a conflict happens during a `git pull`, it is a merging conflict. You can abort the merge falling back to your version of main with:

```sh
git merge --abort
```

or decide to use others version of a file with:

```sh
git checkout --theirs path/to/file
git add path/to/file
git merge --continue
```

or manually fix the conflict and then commit.


See [this post](https://stackoverflow.com/questions/10697463/resolve-git-merge-conflicts-in-favor-of-their-changes-during-a-pull) for more information.


If you want to lose your latest commits (not only the working directory changes) and use the upstream version (origin/main version) you can revert to the HEAD version:

```sh
# backup your main branch
git branch main_bak
# update to 'origin/main'
git fetch
# BEWARE THIS IS A DESTRUCTIVE OPERATION IF YOU DID NOT MAKE
# THE 'main_bak' branch correctly:
git reset --hard origin/main
```

To find your old version:

```sh
git checkout main_bak
```



## References

- Configure RStudio and Git guide: <https://www.geo.uzh.ch/microsite/reproducible_research/post/rr-rstudio-git/>
- Learn git commands used by RStudio: <https://rviews.rstudio.com/2020/04/23/10-commands-to-get-started-with-git/>
- [Git cheatsheet](https://phoenixnap.com/kb/git-commands-cheat-sheet)
- Learn git visually: <http://git-school.github.io/visualizing-git/>
- Other resources: <https://try.github.io/>
- Git Flow: <https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow>
